const ShopDatabase = [
    {
      img: "/images/product-1-1 - Copy.jpg",
      type: "Snack",
      name: "Dandy Blend",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 50,
      id: "1",
      mrp: 100,
      description: "Indulge in the rich and aromatic Dandy Blend, a delightful snack that satisfies your cravings. Crafted from premium coffee beans, chicory, and dandelion root, this unique blend offers a symphony of flavors, combining the boldness of coffee with the earthy notes of dandelion. Each sip takes you on a journey of indulgence, making it a perfect companion for your moments of relaxation and reflection.",
    },
    {
      img: "/images/product-2-1 - Copy.jpg",
      type: "Snack",
      name: "Cashew Mix",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 60,
      id: "2",
      mrp: 120,
      description: "Experience the perfect harmony of crunchiness and flavor with Cashew Mix, a delectable snack crafted for those who savor the finer things in life. This delightful mix features premium cashews, almonds, and pistachios, roasted to perfection and seasoned with a blend of exotic spices. Each bite is a celebration of texture and taste, making it an irresistible treat for any occasion.",
    },
    {
      img: "/images/product-3-1 - Copy.jpg",
      type: "Snack",
      name: "Sweet Potato",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 70,
      id: "3",
      mrp: 140,
      description: "Savor the natural sweetness of Sweet Potato, a healthy and delicious snack that brings joy to your taste buds. Packed with essential nutrients and fiber, these roasted sweet potato bites offer a guilt-free indulgence. Experience the perfect balance of crispy exterior and tender goodness with every delightful bite.",
    },
    {
      img: "/images/product-4-1 - Copy.jpg",
      type: "Snack",
      name: "Peanuts Cracker",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 80,
      id: "4",
      mrp: 160,
      description: "Crunch into the delightful Peanuts Cracker, a perfect blend of roasted peanuts and savory crackers. This satisfying snack delivers a symphony of flavors with each crispy bite. Whether enjoyed on its own or paired with your favorite dip, this snack is a savory treat for all occasions.",
    },
    {
      img: "/images/product-6-1 - Copy.jpg",
      type: "Snack",
      name: "Uliaa Juice",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 90,
      id: "5",
      mrp: 180,
      description: "Quench your thirst with the refreshing Uliaa Juice, a delicious blend of tropical fruits and natural sweetness. This invigorating beverage is perfect for a sunny day or as a delightful accompaniment to your meals. Enjoy the burst of fruity goodness with every sip.",
    },
    {
      img: "/images/product-7-1 - Copy.jpg",
      type: "Snack",
      name: "Sweets Pista",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 100,
      id: "6",
      mrp: 200,
      description: "Indulge in the richness of Sweets Pista, a delightful snack that combines the creamy texture of pistachios with a hint of sweetness. Each pistachio is carefully coated, creating a perfect balance of flavors. Elevate your snacking experience with this irresistible treat.",
    },
    {
      img: "/images/product-8-1 - Copy.jpg",
      type: "Snack",
      name: "Yuija Nuican",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 110,
      id: "7",
      mrp: 220,
      description: "Experience the bold and savory flavors of Yuija Nuican, a snack that tantalizes your taste buds with a perfect blend of spices and crunchiness. Made from premium ingredients, this unique snack is a delightful treat for those who seek bold and exotic flavors.",
    },
    {
      img: "/images/product-9-1 - Copy.jpg",
      type: "Snack",
      name: "Green Tea with Snacks",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 120,
      id: "8",
      mrp: 240,
      description: "Sip on the soothing Green Tea with Snacks, a perfect combination of refreshing green tea and a curated selection of snacks. This unique pairing offers a delightful experience, balancing the calming effects of green tea with the satisfying crunch of savory snacks. Elevate your tea time with this harmonious blend.",
    },
    {
      img: "/images/product-9-1 - Copy.jpg",
      type: "Snack",
      name: "Green Tea with Snacks",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 120,
      id: "9",
      mrp: 240,
      description: "Sip on the soothing Green Tea with Snacks, a perfect combination of refreshing green tea and a curated selection of snacks. This unique pairing offers a delightful experience, balancing the calming effects of green tea with the satisfying crunch of savory snacks. Elevate your tea time with this harmonious blend.",
    },
    {
      img: "/images/product-1-1 - Copy.jpg",
      type: "Snack",
      name: "Dandy Blend",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 50,
      id: "10",
      mrp: 100,
      description: "Indulge in the rich and aromatic Dandy Blend, a delightful snack that satisfies your cravings. Crafted from premium coffee beans, chicory, and dandelion root, this unique blend offers a symphony of flavors, combining the boldness of coffee with the earthy notes of dandelion. Each sip takes you on a journey of indulgence, making it a perfect companion for your moments of relaxation and reflection.",
    },
    {
      img: "/images/product-2-1 - Copy.jpg",
      type: "Snack",
      name: "Cashew Mix",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 60,
      id: "11",
      mrp: 120,
      description: "Experience the perfect harmony of crunchiness and flavor with Cashew Mix, a delectable snack crafted for those who savor the finer things in life. This delightful mix features premium cashews, almonds, and pistachios, roasted to perfection and seasoned with a blend of exotic spices. Each bite is a celebration of texture and taste, making it an irresistible treat for any occasion.",
    },
    {
      img: "/images/product-2-1 - Copy.jpg",
      type: "Snack",
      name: "Cashew Mix",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 60,
      id: "12",
      mrp: 120,
      description: "Experience the perfect harmony of crunchiness and flavor with Cashew Mix, a delectable snack crafted for those who savor the finer things in life. This delightful mix features premium cashews, almonds, and pistachios, roasted to perfection and seasoned with a blend of exotic spices. Each bite is a celebration of texture and taste, making it an irresistible treat for any occasion.",
    },
    {
      img: "/images/product-3-1 - Copy.jpg",
      type: "Snack",
      name: "Sweet Potato",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 70,
      id: "13",
      mrp: 140,
      description: "Savor the natural sweetness of Sweet Potato, a healthy and delicious snack that brings joy to your taste buds. Packed with essential nutrients and fiber, these roasted sweet potato bites offer a guilt-free indulgence. Experience the perfect balance of crispy exterior and tender goodness with every delightful bite.",
    },
    {
      img: "/images/product-4-1 - Copy.jpg",
      type: "Snack",
      name: "Peanuts Cracker",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 80,
      id: "14",
      mrp: 160,
      description: "Crunch into the delightful Peanuts Cracker, a perfect blend of roasted peanuts and savory crackers. This satisfying snack delivers a symphony of flavors with each crispy bite. Whether enjoyed on its own or paired with your favorite dip, this snack is a savory treat for all occasions.",
    },
    {
      img: "/images/product-6-1 - Copy.jpg",
      type: "Snack",
      name: "Uliaa Juice",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 90,
      id: "15",
      mrp: 180,
      description: "Quench your thirst with the refreshing Uliaa Juice, a delicious blend of tropical fruits and natural sweetness. This invigorating beverage is perfect for a sunny day or as a delightful accompaniment to your meals. Enjoy the burst of fruity goodness with every sip.",
    },
    {
      img: "/images/product-7-1 - Copy.jpg",
      type: "Snack",
      name: "Sweets Pista",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 100,
      id: "16",
      mrp: 200,
      description: "Indulge in the richness of Sweets Pista, a delightful snack that combines the creamy texture of pistachios with a hint of sweetness. Each pistachio is carefully coated, creating a perfect balance of flavors. Elevate your snacking experience with this irresistible treat.",
    },
    {
      img: "/images/product-8-1 - Copy.jpg",
      type: "Snack",
      name: "Yuija Nuican",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 110,
      id: "17",
      mrp: 220,
      description: "Experience the bold and savory flavors of Yuija Nuican, a snack that tantalizes your taste buds with a perfect blend of spices and crunchiness. Made from premium ingredients, this unique snack is a delightful treat for those who seek bold and exotic flavors.",
    },
    {
      img: "/images/product-1-1 - Copy.jpg",
      type: "Snack",
      name: "Dandy Blend",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 50,
      id: "18",
      mrp: 100,
      description: "Indulge in the rich and aromatic Dandy Blend, a delightful snack that satisfies your cravings. Crafted from premium coffee beans, chicory, and dandelion root, this unique blend offers a symphony of flavors, combining the boldness of coffee with the earthy notes of dandelion. Each sip takes you on a journey of indulgence, making it a perfect companion for your moments of relaxation and reflection.",
    },
    {
      img: "/images/product-2-1 - Copy.jpg",
      type: "Snack",
      name: "Cashew Mix",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 60,
      id: "19",
      mrp: 120,
      description: "Experience the perfect harmony of crunchiness and flavor with Cashew Mix, a delectable snack crafted for those who savor the finer things in life. This delightful mix features premium cashews, almonds, and pistachios, roasted to perfection and seasoned with a blend of exotic spices. Each bite is a celebration of texture and taste, making it an irresistible treat for any occasion.",
    },
    {
      img: "/images/product-3-1 - Copy.jpg",
      type: "Snack",
      name: "Sweet Potato",
      rating: "(4.0)",
      type1: "Nest Food",
      price: 70,
      id: "20",
      mrp: 140,
      description: "Savor the natural sweetness of Sweet Potato, a healthy and delicious snack that brings joy to your taste buds. Packed with essential nutrients and fiber, these roasted sweet potato bites offer a guilt-free indulgence. Experience the perfect balance of crispy exterior and tender goodness with every delightful bite.",
    },
  ];
  
  export default ShopDatabase;
  